'use client';

import { useEffect, useState } from 'react';
import MultiImageInput, { RefImage } from './MultiImageInput';
import { addWinner, removeWinner } from '@/lib/winners';

// Phase 1 — kie.ai. Only the 3 nano-banana variants we actually use in
// production. More models (flux, midjourney, recraft, etc.) will be added
// in Phase 2 once kie integration is validated.
export const IMAGE_MODELS = [
  { value: 'nano-banana-2', label: 'Nano Banana 2 (default — fast, uses ref image if provided)', needsRef: false, allowsRef: true },
  { value: 'nano-banana-pro', label: 'Nano Banana Pro (best — uses ref image if provided)', needsRef: false, allowsRef: true },
  { value: 'nano-banana', label: 'Nano Banana (original, uses ref image if provided)', needsRef: false, allowsRef: true },
];

interface Props {
  prompt: string;
  /** Pre-loaded reference image(s) provided from the parent form. */
  initialImage?: { base64: string; mimeType: string; previewDataUri: string };
  initialImages?: RefImage[];
  /** Model selected in the main form, used as default */
  initialModel?: string;
  /** When provided, the image is shown immediately (already generated by parent) */
  autoGenerateImageUrl?: string;
  /** Project + generation context for the Winners library star button. */
  projectId?: string;
  generationId?: string;
  assetType?: 'static' | 'iterate';
  /** Stable suffix to disambiguate multiple images inside one generation. */
  assetKeySuffix?: string;
  /** Free-form metadata stored alongside the winner row (format, mode, etc.). */
  winnerMeta?: Record<string, unknown>;
}

export default function PromptImageGenerator({
  prompt,
  initialImage,
  initialImages,
  initialModel,
  autoGenerateImageUrl,
  projectId,
  generationId,
  assetType,
  assetKeySuffix,
  winnerMeta,
}: Props) {
  const [isWinner, setIsWinner] = useState(false);
  // Track the row id returned by /api/winners so we can DELETE it later when
  // the parent didn't provide a generationId (e.g. iterate panel).
  const [winnerRowId, setWinnerRowId] = useState<string | null>(null);
  const winnerEnabled = !!(projectId && assetType);
  const assetKey = `${assetType || 'image'}-${assetKeySuffix || 'main'}`;
  const seedRefs: RefImage[] =
    initialImages && initialImages.length > 0
      ? initialImages
      : initialImage
      ? [initialImage]
      : [];

  const [model, setModel] = useState(initialModel || 'nano-banana-2');
  const [refs, setRefs] = useState<RefImage[]>(seedRefs);
  const [feedback, setFeedback] = useState('');
  const [loading, setLoading] = useState(false);
  const [imageUrl, setImageUrl] = useState(autoGenerateImageUrl || '');
  const [error, setError] = useState('');
  const [isFullscreen, setIsFullscreen] = useState(false);

  // Reset winner flag whenever the underlying image changes (regeneration,
  // refinement, reset). The new image hasn't been starred yet.
  useEffect(() => { setIsWinner(false); setWinnerRowId(null); }, [imageUrl]);

  // Close fullscreen on Escape
  useEffect(() => {
    if (!isFullscreen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setIsFullscreen(false);
    };
    window.addEventListener('keydown', onKey);
    // Lock body scroll while modal open
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [isFullscreen]);

  const currentModel = IMAGE_MODELS.find((m) => m.value === model)!;

  const urlToBase64 = async (url: string): Promise<{ base64: string; mimeType: string } | null> => {
    try {
      const res = await fetch(url);
      const blob = await res.blob();
      const mimeType = blob.type || 'image/png';
      const base64: string = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => {
          const result = reader.result as string;
          // strip "data:<mime>;base64," prefix
          resolve(result.split(',')[1] || '');
        };
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
      return { base64, mimeType };
    } catch {
      return null;
    }
  };

  const generate = async (withFeedback = false) => {
    if (currentModel.needsRef && refs.length === 0) {
      setError('This model requires a reference image — please upload one above.');
      return;
    }

    setLoading(true);
    setError('');

    // When regenerating with feedback AND the model supports refs, send
    // BOTH the previously generated image (so the model edits the existing
    // composition rather than starting from scratch) AND the original
    // product reference photos (so the product identity stays anchored to
    // the real product, not whatever drift the previous image had).
    //
    // The earlier version sent ONLY the previous image, with the comment
    // "the product refs were already baked into the previous image" — that
    // assumption was wrong: if the previous generation drifted on the
    // product, iterating from it just amplifies the drift.
    //
    // nano-banana-2 supports up to 14 reference images, so there's plenty
    // of headroom. Ordering: previous output FIRST (anchors layout +
    // composition), product refs AFTER (anchors product identity).
    const productRefs: Array<{ base64: string; mimeType: string }> = refs.map(
      (r) => ({ base64: r.base64, mimeType: r.mimeType }),
    );
    let sendRefs: Array<{ base64: string; mimeType: string }> = [];
    if (withFeedback && imageUrl && currentModel.allowsRef) {
      const prev = await urlToBase64(imageUrl);
      if (prev) {
        sendRefs = [prev, ...productRefs];
      } else {
        // Couldn't fetch the previous image — fall back to original refs
        sendRefs = productRefs;
      }
    } else if (currentModel.allowsRef) {
      sendRefs = productRefs;
    }

    try {
      const res = await fetch('/api/generate/image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt,
          model,
          referenceImages: sendRefs.length > 0 ? sendRefs : undefined,
          feedback: withFeedback ? feedback : undefined,
          // Sent so the API can persist a Generation row (history thumbnail).
          projectId,
        }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({ error: `Server error ${res.status}` }));
        setError(err.error || `Error ${res.status}`);
        setLoading(false);
        return;
      }

      const data = await res.json();
      setImageUrl(data.imageUrl);
      if (withFeedback) setFeedback('');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Unexpected error');
    }

    setLoading(false);
  };

  const downloadImage = () => {
    if (!imageUrl) return;
    // Use our server-side proxy so the browser sees a same-origin response
    // with Content-Disposition: attachment — triggers a real download dialog
    // instead of opening the image in a new tab (which is what cross-origin
    // R2 / Fal URLs do otherwise).
    const filename = `generated-${Date.now()}.png`;
    const proxyUrl = `/api/download-image?url=${encodeURIComponent(imageUrl)}&filename=${encodeURIComponent(filename)}`;
    const a = document.createElement('a');
    a.href = proxyUrl;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="border border-bg-border rounded-lg p-4 mt-3 bg-bg-base/50 space-y-3">
      <div className="flex items-center justify-between">
        <span className="text-text-secondary text-xs uppercase tracking-widest">Generate image with AI</span>
      </div>

      {/* Model selector */}
      <div>
        <label className="text-text-muted text-[10px] uppercase tracking-widest block mb-1">Model</label>
        <select
          className="input-field text-xs"
          value={model}
          onChange={(e) => {
            setModel(e.target.value);
            setImageUrl('');
            setError('');
          }}
        >
          {IMAGE_MODELS.map((m) => (
            <option key={m.value} value={m.value}>{m.label}</option>
          ))}
        </select>
      </div>

      {/* Reference image(s) — only if model supports it */}
      {currentModel.allowsRef && (
        <div>
          <label className="text-text-muted text-[10px] uppercase tracking-widest block mb-1">
            Product reference photo(s) {currentModel.needsRef ? '*' : '(optional — multiple allowed)'}
          </label>
          <MultiImageInput
            images={refs}
            onChange={setRefs}
            compact
            emptyLabel="↑ Upload product photo(s)"
          />
        </div>
      )}

      {/* Generate button (only if no image yet) */}
      {!imageUrl && !loading && (
        <button
          onClick={() => generate(false)}
          className="btn-primary w-full text-xs"
          disabled={loading || (currentModel.needsRef && refs.length === 0)}
        >
          Generate image
        </button>
      )}

      {/* Loading */}
      {loading && (
        <div className="flex items-center justify-center py-8">
          <div className="w-6 h-6 border-2 border-accent-gold/30 border-t-accent-gold rounded-full animate-spin" />
          <span className="text-text-muted text-xs ml-3">Generating image…</span>
        </div>
      )}

      {/* Error */}
      {error && !loading && (
        <div className="border border-accent-red/40 bg-accent-red/5 rounded px-3 py-2 text-xs text-accent-red">
          {error}
        </div>
      )}

      {/* Generated image + feedback/regenerate */}
      {imageUrl && !loading && (
        <div className="space-y-3">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageUrl}
            alt="generated"
            onClick={() => setIsFullscreen(true)}
            className="max-w-xs max-h-80 w-auto h-auto rounded-md border border-bg-border mx-auto block cursor-zoom-in hover:opacity-90 transition-opacity"
            title="Click to view full size"
          />

          <div className="flex gap-2">
            {winnerEnabled && (
              <button
                onClick={async () => {
                  const next = !isWinner;
                  setIsWinner(next);
                  if (next) {
                    const created = await addWinner({
                      projectId: projectId!,
                      generationId,
                      assetType: assetType!,
                      assetKey,
                      content: prompt,
                      imageUrl,
                      meta: winnerMeta,
                    });
                    if (created?.id) setWinnerRowId(created.id);
                  } else if (generationId) {
                    await removeWinner(generationId, assetKey);
                    setWinnerRowId(null);
                  } else if (winnerRowId) {
                    // No generationId — DELETE by row id (iterate panel case).
                    await fetch(`/api/winners/${winnerRowId}`, { method: 'DELETE' });
                    setWinnerRowId(null);
                  }
                }}
                className={`text-xs px-3 py-2 rounded border font-medium transition-colors ${
                  isWinner
                    ? 'bg-accent-violet/20 border-accent-violet/60 text-accent-violet'
                    : 'bg-transparent border-bg-border text-text-muted hover:border-accent-violet/40 hover:text-accent-violet'
                }`}
                title={isWinner ? 'Remove from Winners library' : 'Add to Winners library'}
              >
                {isWinner ? '★ Winner' : '☆ Mark Winner'}
              </button>
            )}
            <button onClick={downloadImage} className="btn-secondary text-xs flex-1">
              Download
            </button>
            <button
              onClick={() => { setImageUrl(''); setError(''); setIsWinner(false); }}
              className="btn-secondary text-xs flex-1"
            >
              Reset
            </button>
          </div>

          <div>
            <label className="text-text-muted text-[10px] uppercase tracking-widest block mb-1">
              {currentModel.allowsRef
                ? "What to change on this image? (edits the image above)"
                : "What's wrong? (regenerates from scratch — model doesn't support image edit)"}
            </label>
            <textarea
              className="input-field resize-none text-xs"
              rows={2}
              placeholder="e.g. change the background to beige, make the text bigger, remove the logo top-right…"
              value={feedback}
              onChange={(e) => setFeedback(e.target.value)}
            />
          </div>

          <button onClick={() => generate(true)} className="btn-primary w-full text-xs">
            {currentModel.allowsRef
              ? feedback.trim() ? 'Edit this image with feedback' : 'Regenerate'
              : feedback.trim() ? 'Regenerate with feedback' : 'Regenerate'}
          </button>
        </div>
      )}

      {/* Fullscreen lightbox */}
      {isFullscreen && imageUrl && (
        <div
          onClick={() => setIsFullscreen(false)}
          className="fixed inset-0 z-50 bg-black/90 flex items-center justify-center p-6 cursor-zoom-out"
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageUrl}
            alt="generated full size"
            onClick={(e) => e.stopPropagation()}
            className="max-w-full max-h-full object-contain rounded-md cursor-default"
          />
          <button
            onClick={() => setIsFullscreen(false)}
            className="absolute top-4 right-4 text-white/80 hover:text-white text-2xl w-10 h-10 flex items-center justify-center rounded-full bg-black/50 hover:bg-black/70 transition-colors"
            title="Close (Esc)"
          >
            ✕
          </button>
        </div>
      )}
    </div>
  );
}
